-- Generated by tools/generate-data.ts from the pins in dataset/sources.json. Do not edit.
-- Original Classic quest IDs: QuestieDB (https://github.com/Questie/QuestieDB)
-- data/Classic/classicQuestDB.lua plus Classic Era-only additions from
-- src/corrections/Era/classicQuestFixes.lua, at Questie/QuestieDB@b6f5b07b0acf.
-- Only quest IDs are included; no quest text is redistributed.

local _, ns = ...

ns.Data.Sets.classic = {
	count = 4257,
	segments = {
		{ 2, "5/////H+///f/////v////3////////////////e+/f+/////v//7/8///7/////v/v7////////v////73/////v//+/////////v/+///////////////////+////v/3/DwN77//3//b///////7s/////7//////x/95//////////////f////P////hR/7////fAwHAA//P89vH0DAYAA8HAwAAA///w/7XAAA///f9//8////Hs/////dAAAcAAwHAADAAEAAw///JOA8//w///DAAcAAQAAA///9fAw/AA/fA8AAw/BADAA8AAw////AAEAAwAAAAAA8AAAAAABAAEAAQAAADAA8AAQAAA/HAEAAwHAAHAA8HAwBAABAA8BAwDAA/AAMAAQAAAHAAcAAwBAAPAA8DAACAAIAAgfAA+PA4AAgAAAGAAIAAgBAACAA4/////AeAAIAAgBAA+///v//BAAcAAw/////B8f/////BAAEAAQAAALAA8////9//HACAAIAAgBAACAAIAAAAAACAAIAAgAAACAAIAAgv//lAAQAAgAAA+/H4AAgCAA+/n/fAgBAA+fAAAAgBAAi///PAgAAACAAYAAgAAACAA4DAg/fAeAA4DAgPAACAA4BAg/zBeAAYAAgBAAGAA4DAgHAACAA4AAgHAA+/////h/BACAA4HAgAAAeAA4DAg/AA+//NAAgFAAOAA4AAgfAAOAAIAAg/PA+DA4//h//ACAAQAAgAAACAA4HAgAAAGAAIAAgAAACAA4///DAA+/A4fAg//AGAAYAAg/AAOAA4NAgAAACAA4//h/AAGAA4AAg/f//HA4//HDAA+HA4////BACAA4F////f+/D4DAgHAAmDAIAAgHAACAAYHAg/BACAAIAAgfAAGAA477u9rf+AAIAAgBAACAA4////ffPA/HAAAAgA+fAYAAgDAACAA4DAgAAA+HA4AAg//AeAA4/HgHAACAAIAAgFAA+/BYAAg//H+PA4AAg/3H+HA4BAg/" },
		{ 6261, "BAA8BAQAAAPAA8AAwHAA//HcAAQAAADAAMAAwAAAPAAcAAw/AA/fA8BAw/PA/HA8DAwAAABAAEAAwAAABAAMAAQAAAZAA8HAA+AADAAEAAQAAADAAcAAwDAAfAAcAAw/BA/AA8vAwAAADAA8AAwAAA//AEAAwAAAPAAEAAQAAADAAMAAQAAADAA8PAwNAADAA8fAQAAAHAA87///BAAAAEAAgDAAHAA8AAw/////////DAAANAA8//DAAABAA8f/+////////Aw/8H///fFAw////AAAAAQAAAAAAAAAw//////HAAw///PAA8/9//HA//PEAAw397n8/+f3////////AHwh9//////////////fGA4eHAZg//////5//+/P/+//////P////////////////////////////////////////////BQ8///////////Pw////////n7///fh/9//////7/NGDADABA2/mv/eB8/+//G0//AAAS8CC8/4/VAAg2AIgGAAAwk" },
		{ 65593, "R8g" },
	},
	ids = {
		9664, 9665,
	},
}
