-- Generated by tools/generate-data.ts from the pins in dataset/sources.json. Do not edit.
-- Provenance of the quest ID sets. Shown by /fqm status.

local _, ns = ...

ns.Data.meta = {
	questieDB = "Questie/QuestieDB@b6f5b07b0acf",
	foreverBuild = "1.60.1.69977",
	eraBuild = "1.15.9.69722",
	counts = {
		classic = 4257,
		sod = 928,
		era = 495,
		datamined = 1792,
		community = 0,
		changed = 0,
	},
}
