import { encodeSet, type EncodedSet } from "./bitset";
import type { BuildResult, QuestSets } from "./build";

const HEADER =
  "-- Generated by tools/generate-data.ts from the pins in dataset/sources.json. Do not edit.";
const IDS_PER_LINE = 16;

function wrapNumbers(ids: readonly number[], indent: string): string {
  const lines: string[] = [];
  for (let i = 0; i < ids.length; i += IDS_PER_LINE) {
    lines.push(indent + ids.slice(i, i + IDS_PER_LINE).join(", ") + ",");
  }
  return lines.join("\n");
}

function luaSet(name: string, set: EncodedSet): string {
  const segments = set.segments
    .map((segment) => `\t\t{ ${segment.offset}, "${segment.bits}" },`)
    .join("\n");
  const ids =
    set.ids.length > 0 ? `\n${wrapNumbers(set.ids, "\t\t")}\n\t` : " ";
  return [
    `ns.Data.Sets.${name} = {`,
    `\tcount = ${set.count},`,
    set.segments.length > 0
      ? `\tsegments = {\n${segments}\n\t},`
      : "\tsegments = {},",
    `\tids = {${ids}},`,
    "}",
  ].join("\n");
}

function luaFile(description: string[], body: string[]): string {
  return [
    HEADER,
    ...description.map((line) => `-- ${line}`),
    "",
    "local _, ns = ...",
    "",
    body.join("\n\n"),
    "",
  ].join("\n");
}

export interface EmittedFiles {
  [relativePath: string]: string;
}

export function emitAll(result: BuildResult): EmittedFiles {
  const { sets, pins } = result;
  const questie = `${pins.questieDB.repo}@${pins.questieDB.commit.slice(0, 12)}`;
  const encoded = Object.fromEntries(
    Object.entries(sets).map(([name, ids]) => [name, encodeSet(ids)]),
  ) as Record<keyof QuestSets, EncodedSet>;

  const files: EmittedFiles = {};

  files["Data/Meta.lua"] = luaFile(
    ["Provenance of the quest ID sets. Shown by /fqm status."],
    [
      [
        "ns.Data.meta = {",
        `\tquestieDB = "${questie}",`,
        `\tforeverBuild = "${pins.wago.foreverBuild}",`,
        `\teraBuild = "${pins.wago.eraBuild}",`,
        "\tcounts = {",
        ...Object.entries(sets).map(
          ([name, ids]) => `\t\t${name} = ${ids.length},`,
        ),
        "\t},",
        "}",
      ].join("\n"),
    ],
  );

  files["Data/ClassicQuests.lua"] = luaFile(
    [
      "Original Classic quest IDs: QuestieDB (https://github.com/Questie/QuestieDB)",
      `${pins.questieDB.classicQuestDB} plus Classic Era-only additions from`,
      `${pins.questieDB.eraQuestFixes}, at ${questie}.`,
      "Only quest IDs are included; no quest text is redistributed.",
    ],
    [luaSet("classic", encoded.classic)],
  );

  files["Data/ForeverQuests.lua"] = luaFile(
    [
      "Quests that are new or modified in WoW Forever.",
      `datamined: in the Forever client's QuestV2 table (build ${pins.wago.foreverBuild}) but not in`,
      `  the Classic Era client's (build ${pins.wago.eraBuild}), via https://wago.tools.`,
      "community: confirmed by player reports (dataset/community/confirmed.json).",
      "changed: original Classic quests confirmed as modified (dataset/community/changed.json).",
    ],
    [
      luaSet("datamined", encoded.datamined),
      luaSet("community", encoded.community),
      luaSet("changed", encoded.changed),
    ],
  );

  files["Data/Exclusions.lua"] = luaFile(
    [
      "Quests that are not original Classic but are not new in WoW Forever either.",
      `sod: Season of Discovery quests from ${pins.questieDB.sodBaseQuests} at ${questie}.`,
      `era: other quests present in the Classic Era client (build ${pins.wago.eraBuild}),`,
      "  such as cut, unused or event quests that QuestieDB does not list.",
    ],
    [luaSet("sod", encoded.sod), luaSet("era", encoded.era)],
  );

  files["tests/fixtures/quest_sets.lua"] = [
    HEADER,
    "-- Plain ID lists used by the busted specs to verify the encoded sets.",
    "return {",
    ...Object.entries(sets).map(
      ([name, ids]) => `\t${name} = {\n${wrapNumbers(ids, "\t\t")}\n\t},`,
    ),
    "}",
    "",
  ].join("\n");

  const tsArray = (ids: readonly number[]) => `[\n${wrapNumbers(ids, "  ")}\n]`;
  files["worker/src/generated/questData.ts"] = [
    HEADER.replace(/^--/, "//"),
    "",
    "export const QUEST_DATA_META = {",
    `  questieDB: "${questie}",`,
    `  foreverBuild: "${pins.wago.foreverBuild}",`,
    `  eraBuild: "${pins.wago.eraBuild}",`,
    "} as const;",
    "",
    `export const CLASSIC_QUEST_IDS: readonly number[] = ${tsArray(sets.classic)};`,
    "",
    `export const SOD_QUEST_IDS: readonly number[] = ${tsArray(sets.sod)};`,
    "",
    `export const ERA_CLIENT_QUEST_IDS: readonly number[] = ${tsArray(sets.era)};`,
    "",
    `export const DATAMINED_FOREVER_QUEST_IDS: readonly number[] = ${tsArray(sets.datamined)};`,
    "",
    `export const COMMUNITY_CONFIRMED_QUEST_IDS: readonly number[] = ${tsArray(sets.community)};`,
    "",
    `export const CHANGED_QUEST_IDS: readonly number[] = ${tsArray(sets.changed)};`,
    "",
  ].join("\n");

  return files;
}
