-- Builds tests/helpers/widget_api.lua from the client's widget API documentation so
-- the test mocks reject any widget method the target client does not have.
--
-- Usage: luajit tools/gen-widget-api.lua <wow-ui-source>/Interface/AddOns/Blizzard_APIDocumentationGenerated [build]

local docsDir, build = arg[1], arg[2] or "unknown"
assert(docsDir, "usage: luajit tools/gen-widget-api.lua <Blizzard_APIDocumentationGenerated dir> [build]")

local documents = {}

-- The documentation files reference enum and constant tables; any value will do.
local function Permissive()
	return setmetatable({}, { __index = function(t, k)
		local v = Permissive()
		rawset(t, k, v)
		return v
	end })
end
Enum = Permissive()
Constants = Permissive()

APIDocumentation = {
	AddDocumentationTable = function(_, tbl)
		documents[tbl.Name] = tbl
	end,
}

local function load(name)
	local chunk = assert(loadfile(docsDir .. "/" .. name .. "Documentation.lua"))
	chunk()
end

local sources = {
	"SimpleObjectAPI", "SimpleFrameScriptObjectAPI", "SimpleScriptRegionAPI",
	"SimpleScriptRegionResizingAPI", "SimpleRegionAPI", "SimpleAnimatableObjectAPI",
	"SimpleTextureBaseAPI", "SimpleTextureAPI", "SimpleFontStringAPI", "SimpleFontAPI",
	"SimpleFrameAPI", "SimpleButtonAPI", "SimpleEditBoxAPI", "SimpleScrollFrameAPI",
}
for _, name in ipairs(sources) do
	load(name)
end

-- Widget types and the documented API groups each one exposes.
local REGION = {
	"SimpleObjectAPI", "SimpleFrameScriptObjectAPI", "SimpleScriptRegionAPI",
	"SimpleScriptRegionResizingAPI", "SimpleAnimatableObjectAPI",
}
local function With(...)
	local groups = { unpack(REGION) }
	for i = 1, select("#", ...) do
		table.insert(groups, (select(i, ...)))
	end
	return groups
end
local widgetTypes = {
	Texture = With("SimpleRegionAPI", "SimpleTextureBaseAPI", "SimpleTextureAPI"),
	FontString = With("SimpleRegionAPI", "SimpleFontStringAPI", "SimpleFontAPI"),
	Frame = With("SimpleFrameAPI"),
	Button = With("SimpleFrameAPI", "SimpleButtonAPI"),
	EditBox = With("SimpleFrameAPI", "SimpleEditBoxAPI", "SimpleFontAPI"),
	ScrollFrame = With("SimpleFrameAPI", "SimpleScrollFrameAPI"),
}

local typeNames = {}
for typeName in pairs(widgetTypes) do
	table.insert(typeNames, typeName)
end
table.sort(typeNames)

local out = {
	"-- Generated by tools/gen-widget-api.lua from the client's widget API documentation",
	("-- (build %s). Do not edit."):format(build),
	"return {",
}
for _, typeName in ipairs(typeNames) do
	local methods = {}
	for _, group in ipairs(widgetTypes[typeName]) do
		local doc = assert(documents[group], "missing documentation table " .. group)
		for _, fn in ipairs(doc.Functions or {}) do
			methods[fn.Name] = true
		end
	end
	local names = {}
	for name in pairs(methods) do
		table.insert(names, name)
	end
	table.sort(names)
	table.insert(out, ("\t%s = {"):format(typeName))
	for _, name in ipairs(names) do
		table.insert(out, ("\t\t%s = true,"):format(name))
	end
	table.insert(out, "\t},")
end
table.insert(out, "}")
table.insert(out, "")

local file = assert(io.open("tests/helpers/widget_api.lua", "w"))
file:write(table.concat(out, "\n"))
file:close()
print(("wrote tests/helpers/widget_api.lua for %d widget types"):format(#typeNames))
